version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - ollama:/root/.ollama
      - ./scripts/entrypoint.sh:/entrypoint.sh:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - X_API_BEARER_TOKEN=${X_API_BEARER_TOKEN}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NOTIFICATION_DRIVER=${NOTIFICATION_DRIVER}
    depends_on:
      - ollama
    ports:
      - "3000:3000"

volumes:
  ollama:
